# Generated by Django 2.0.5 on 2019-06-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[(0, '系統管理員'), (1, '宿舍管理員'), (2, '住宿生'), (3, '學生')], default=3)),
                ('phone', models.CharField(default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=512)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('content', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('Unpaid', '未繳費'), ('Paid', '已繳費'), ('Expired', '過期')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('memo', models.CharField(max_length=512)),
                ('confirm', models.IntegerField(choices=[(0, '等待核可中'), (1, '核可完成'), (2, '退件')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('point', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DormInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=2)),
                ('room', models.CharField(max_length=8)),
                ('bed', models.IntegerField()),
                ('status', models.CharField(choices=[('None', '沒有住人'), ('Forbid', '不能住'), ('Lived', '有住人')], default='None', max_length=16)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DormRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order1', models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')])),
                ('order2', models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')])),
                ('order3', models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('tag', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('current_state', models.CharField(choices=[('Free', '可借用'), ('InUse', '出借中'), ('NotAvailable', '不可使用')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Mail', '信件'), ('Package', '包裹'), ('Prompt', '限時')], max_length=10)),
                ('sender', models.CharField(max_length=32)),
                ('verify', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Repairment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('AC', '冷氣'), ('Furnitures', '家具'), ('Bathroom', '浴室'), ('Others', '其他')], max_length=16)),
                ('content', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('Reported', '已回報'), ('Pending', '等待中'), ('WIP', '修復中'), ('Done', '已完成')], max_length=16)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accused', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Noise', '噪音'), ('Dirty', '髒亂'), ('Intrusion', '闖入'), ('Others', '其他')], max_length=16)),
                ('content', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('Reported', '已回報'), ('Pending', '等待中'), ('WIP', '處理中'), ('Done', '已完成')], max_length=16)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('department', models.CharField(max_length=16)),
                ('grade', models.CharField(choices=[('1', '一年級'), ('2', '二年級'), ('3', '三年級'), ('4', '四年級')], max_length=1)),
                ('room', models.CharField(max_length=8, null=True)),
                ('bed', models.IntegerField(null=True)),
                ('conduct', models.PositiveSmallIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateField()),
                ('EndTime', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Equipment'),
        ),
    ]
