# Generated by Django 2.0.5 on 2019-05-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
