# Generated by Django 2.0.5 on 2019-05-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Permission',
            new_name='permission',
        ),
    ]
