# Generated by Django 2.0.5 on 2019-06-14 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateField()),
                ('EndTime', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='state',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='confirm',
            field=models.IntegerField(choices=[(0, '等待核可中'), (1, '核可完成'), (2, '退件')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 0, 48, 0, 348965)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 0, 48, 7, 634628)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dorminfo',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Forbid', '不能住'), ('None', '沒有住人'), ('Lived', '有住人')], default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='package',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairment',
            name='location',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='accused',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='state',
            field=models.CharField(choices=[('Unpaid', '未繳費'), ('Paid', '已繳費'), ('Expired', '過期')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dormrecord',
            name='order1',
            field=models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')]),
        ),
        migrations.AlterField(
            model_name='dormrecord',
            name='order2',
            field=models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')]),
        ),
        migrations.AlterField(
            model_name='dormrecord',
            name='order3',
            field=models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
