# Generated by Django 2.0.5 on 2019-06-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('point', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.AddField(
            model_name='repairment',
            name='location',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='accused',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='conduct',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('None', '沒有住人'), ('Lived', '有住人'), ('Forbid', '不能住')], default='None', max_length=16),
        ),
    ]
