# Generated by Django 2.0.5 on 2019-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
