# Generated by Django 2.0.5 on 2019-06-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0002_auto_20190614_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='conduct',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Lived', '有住人'), ('Forbid', '不能住'), ('None', '沒有住人')], default='None', max_length=16),
        ),
    ]
