# Generated by Django 2.0.5 on 2019-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0002_package_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Lived', '有住人'), ('Forbid', '不能住'), ('None', '沒有住人')], default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('lounge', '交誼廳'), ('ReadingRoom', '閱覽室'), ('Kitchen', '廚房'), ('Others', '其他')], default='None', max_length=8),
            preserve_default=False,
        ),
    ]
