# Generated by Django 2.0.5 on 2019-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0002_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='permission',
            field=models.IntegerField(choices=[(0, '系統管理員'), (1, '宿舍管理員'), (2, '住宿生'), (3, '學生')], default=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
