# Generated by Django 2.0.5 on 2019-06-03 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0002_package_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('lounge', '交誼廳'), ('ReadingRoom', '閱覽室'), ('Kitchen', '廚房'), ('Others', '其他')], default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairment',
            name='location',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
