# Generated by Django 2.0.5 on 2019-06-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0003_auto_20190529_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='studentID',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='name',
        ),
        migrations.AlterField(
            model_name='billboard',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account'),
        ),
        migrations.AlterField(
            model_name='repairment',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account'),
        ),
        migrations.AlterField(
            model_name='report',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account'),
        ),
    ]
