# Generated by Django 2.0.5 on 2019-06-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0003_auto_20190603_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorminfo',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
