# Generated by Django 2.0.5 on 2019-06-15 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0003_auto_20190614_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('point', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Lived', '有住人'), ('None', '沒有住人'), ('Forbid', '不能住')], default='None', max_length=16),
        ),
    ]
