# Generated by Django 2.0.5 on 2019-06-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0004_auto_20190530_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('Mail', '信件'), ('Package', '包裹'), ('Prompt', '限時')], max_length=4),
        ),
    ]
