# Generated by Django 2.0.5 on 2019-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0005_auto_20190606_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='account',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='tag',
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Forbid', '不能住'), ('None', '沒有住人'), ('Lived', '有住人')], default='None', max_length=16),
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
