# Generated by Django 2.0.5 on 2019-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0005_auto_20190601_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('Mail', '信件'), ('Package', '包裹'), ('Prompt', '限時')], max_length=10),
        ),
    ]
