# Generated by Django 2.0.5 on 2019-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0006_auto_20190601_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
