# Generated by Django 2.0.5 on 2019-06-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0006_auto_20190606_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('memo', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('Free', '可借用'), ('InUse', '出借中'), ('NotAvailable', '不可使用')], max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('tag', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('current_state', models.CharField(choices=[('Free', '可借用'), ('InUse', '出借中'), ('NotAvailable', '不可使用')], max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('None', '沒有住人'), ('Forbid', '不能住'), ('Lived', '有住人')], default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AS.Equipment'),
        ),
    ]
