# Generated by Django 2.0.5 on 2019-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0007_package_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('lounge', '交誼廳'), ('ReadingRoom', '閱覽室'), ('Kitchen', '廚房'), ('Others', '其他')], default=None, max_length=8),
            preserve_default=False,
        ),
    ]
