# Generated by Django 2.0.5 on 2019-06-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0008_auto_20190606_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='state',
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Lived', '有住人'), ('Forbid', '不能住'), ('None', '沒有住人')], default='None', max_length=16),
        ),
    ]
