# Generated by Django 2.0.5 on 2019-06-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0009_auto_20190606_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='confirm',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='state',
            field=models.CharField(choices=[('Unpaid', '未繳費'), ('Paid', '已繳費'), ('Expired', '過期')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Forbid', '不能住'), ('None', '沒有住人'), ('Lived', '有住人')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='dormrecord',
            name='order1',
            field=models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')]),
        ),
        migrations.AlterField(
            model_name='dormrecord',
            name='order2',
            field=models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')]),
        ),
        migrations.AlterField(
            model_name='dormrecord',
            name='order3',
            field=models.IntegerField(choices=[(0, '綜宿'), (1, 'OA'), (2, 'OB'), (3, 'OE'), (4, 'OF')]),
        ),
    ]
