# Generated by Django 2.0.5 on 2019-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0010_auto_20190611_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='confirm',
            field=models.CharField(choices=[(0, '等待核可中'), (1, '核可完成'), (2, '退件')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Lived', '有住人'), ('None', '沒有住人'), ('Forbid', '不能住')], default='None', max_length=16),
        ),
    ]
