# Generated by Django 2.0.5 on 2019-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0011_auto_20190611_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='confirm',
            field=models.IntegerField(choices=[(0, '等待核可中'), (1, '核可完成'), (2, '退件')]),
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('None', '沒有住人'), ('Lived', '有住人'), ('Forbid', '不能住')], default='None', max_length=16),
        ),
    ]
