# Generated by Django 2.0.5 on 2019-06-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0012_auto_20190611_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Forbid', '不能住'), ('Lived', '有住人'), ('None', '沒有住人')], default='None', max_length=16),
        ),
    ]
