# Generated by Django 2.0.5 on 2019-06-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0013_auto_20190612_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateField()),
                ('EndTime', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('Forbid', '不能住'), ('None', '沒有住人'), ('Lived', '有住人')], default='None', max_length=16),
        ),
    ]
