# Generated by Django 2.0.5 on 2019-06-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS', '0014_auto_20190612_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorminfo',
            name='status',
            field=models.CharField(choices=[('None', '沒有住人'), ('Forbid', '不能住'), ('Lived', '有住人')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='package',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
